Added to About Page
rileycleavenger/StockBuddy pull request #16
Opened 2024-06-03 18:15 UTC by Dravani

Issue 15: Implement About Page

Added Descriptions, Images, and Personal Info of the Team. If you would like me to change anything, let me know.

2024-06-11 01:38 UTC, rileycleavenger requested changes
<img width="1438" alt="image" src="https://github.com/rileycleavenger/StockBuddy/assets/73538882/e3e31581-5ea9-4d76-9898-9a58e6071fc2">

For smaller screens you should have the ones that drop down to the next line center in the second row. Also fix the typos, add a slight margin or padding to the top of the page, and switch the "LinkedIn" and "GitHub" to icons (for that you can probably use font awesome or something similar). Other than that it looks really good!

2024-06-11 01:38 UTC, rileycleavenger commented on my-ai-stock-buddy/src/pages/AboutPage.tsx
> +          <p className='About-Summary'>Stock Buddy is a comprehensive stock market anaylsis tool developed by a group of dedicated college students. Our goal is to
a few typos in here

2024-06-11 01:38 UTC, rileycleavenger commented on my-ai-stock-buddy/src/components/TeamMemberCard.tsx
> +        <a href={member.linkedin} target="_blank" rel="noopener noreferrer">LinkedIn</a>
I think these would be better as logo icons

2024-06-11 01:49 UTC, dos-2 approved these changes
Once you've completed riley's changes and get his approval, you're good to go!

2024-06-13 01:53 UTC, rileycleavenger approved these changes
LGTM!

2024-06-13 01:53 UTC, merged