Navigation bar styled. Live updating underlined location based on act…
rileycleavenger/StockBuddy pull request #19
Opened 2024-06-11 01:04 UTC by madwirblet

CSS for the navigation bar. Underlines the active tab on the website.

2024-06-11 01:41 UTC, rileycleavenger requested changes
It looks so good!!. Only thing I would say is just replace the logo with a higher quality version of the image if possible.

2024-06-11 01:41 UTC, rileycleavenger commented on my-ai-stock-buddy/src/components/Nav/images/StockBuddyLogo.png
I love this logo, but do you have a higher quality/larger version that you could replace this file with so it appears more high quality in the nav bar?

2024-06-11 23:41 UTC, madwirblet commented on my-ai-stock-buddy/src/components/Nav/images/StockBuddyLogo.png
Updated the logo to be high res

2024-06-13 01:54 UTC, rileycleavenger approved these changes
LGTM! Nice work!

2024-06-13 01:54 UTC, merged